/******************************* LICENCE **************************************
* Any code in this file may be redistributed or modified under the terms of
* the GNU General Public Licence as published by the Free Software 
* Foundation; version 2 of the licence.
****************************** END LICENCE ***********************************/

/******************************************************************************
* Author:
* Andrew Smith, http://littlesvr.ca/misc/contactandrew.php
*
* Contributors:
* 
******************************************************************************/

#include <stdio.h>
#include <sys/types.h>

#include "bkInternal.h"
#include "bkError.h"

struct MessageStruct
{
    int number;
    const char* text;
};

const struct MessageStruct messageStructs[] = 
{
    { BKERROR_READ_GENERIC, BKERROR_READ_GENERIC_TEXT },
    { BKERROR_DIR_NOT_FOUND_ON_IMAGE, BKERROR_DIR_NOT_FOUND_ON_IMAGE_TEXT },
    { BKERROR_MAX_NAME_LENGTH_EXCEEDED, BKERROR_MAX_NAME_LENGTH_EXCEEDED_TEXT },
    { BKERROR_STAT_FAILED, BKERROR_STAT_FAILED_TEXT },
    { BKERROR_TARGET_NOT_A_DIR, BKERROR_TARGET_NOT_A_DIR_TEXT },
    { BKERROR_OUT_OF_MEMORY, BKERROR_OUT_OF_MEMORY_TEXT },
    { BKERROR_OPENDIR_FAILED, BKERROR_OPENDIR_FAILED_TEXT },
    { BKERROR_EXOTIC, BKERROR_EXOTIC_TEXT },
    { BKERROR_FIXME, BKERROR_FIXME_TEXT },
    { BKERROR_FILE_NOT_FOUND_ON_IMAGE, BKERROR_FILE_NOT_FOUND_ON_IMAGE_TEXT },
    { BKERROR_MKDIR_FAILED, BKERROR_MKDIR_FAILED_TEXT },
    { BKERROR_OPEN_WRITE_FAILED, BKERROR_OPEN_WRITE_FAILED_TEXT },
    { BKERROR_WRITE_GENERIC, BKERROR_WRITE_GENERIC_TEXT },
    { BKERROR_MANGLE_TOO_MANY_COL, BKERROR_MANGLE_TOO_MANY_COL_TEXT },
    { BKERROR_MISFORMED_PATH, BKERROR_MISFORMED_PATH_TEXT },
    { BKERROR_INVALID_UCS2, BKERROR_INVALID_UCS2_TEXT },
    { BKERROR_UNKNOWN_FILENAME_TYPE, BKERROR_UNKNOWN_FILENAME_TYPE_TEXT },
    { BKERROR_RR_FILENAME_MISSING, BKERROR_RR_FILENAME_MISSING_TEXT },
    { BKERROR_VD_NOT_PRIMARY, BKERROR_VD_NOT_PRIMARY_TEXT },
    { BKERROR_SANITY, BKERROR_SANITY_TEXT },
    { BKERROR_OPEN_READ_FAILED, BKERROR_OPEN_READ_FAILED_TEXT },
    { BKERROR_DIRNAME_NEED_TRAILING_SLASH, BKERROR_DIRNAME_NEED_TRAILING_SLASH_TEXT },
    { BKERROR_EXTRACT_ROOT, BKERROR_EXTRACT_ROOT_TEXT },
    { BKERROR_DELETE_ROOT, BKERROR_DELETE_ROOT_TEXT },
    { BKERROR_DUPLICATE_ADD, BKERROR_DUPLICATE_ADD_TEXT },
    { BKERROR_DUPLICATE_EXTRACT, BKERROR_DUPLICATE_EXTRACT_TEXT },
    { BKERROR_NO_SPECIAL_FILES, BKERROR_NO_SPECIAL_FILES_TEXT },
    { BKERROR_NO_POSIX_PRESENT, BKERROR_NO_POSIX_PRESENT_TEXT },
    { BKERROR_EXTRACT_ABSENT_BOOT_RECORD, BKERROR_EXTRACT_ABSENT_BOOT_RECORD_TEXT },
    { BKERROR_EXTRACT_UNKNOWN_BOOT_MEDIA, BKERROR_EXTRACT_UNKNOWN_BOOT_MEDIA_TEXT },
    { BKERROR_ADD_UNKNOWN_BOOT_MEDIA, BKERROR_ADD_UNKNOWN_BOOT_MEDIA_TEXT },
    { BKERROR_ADD_BOOT_RECORD_WRONG_SIZE, BKERROR_ADD_BOOT_RECORD_WRONG_SIZE_TEXT },
    { BKERROR_WRITE_BOOT_FILE_4, BKERROR_WRITE_BOOT_FILE_4_TEXT },
    { BKERROR_DUPLICATE_CREATE_DIR, BKERROR_DUPLICATE_CREATE_DIR_TEXT },
    { BKERROR_NAME_INVALID_CHAR, BKERROR_NAME_INVALID_CHAR_TEXT },
    { BKERROR_BLANK_NAME, BKERROR_BLANK_NAME_TEXT },
    { BKERROR_ADD_FILE_TOO_BIG, BKERROR_ADD_FILE_TOO_BIG_TEXT },
    { BKERROR_SAVE_OVERWRITE, BKERROR_SAVE_OVERWRITE_TEXT },
    { BKERROR_OPER_CANCELED_BY_USER, BKERROR_OPER_CANCELED_BY_USER_TEXT },
    { BKERROR_WRONG_EXTRACT_FILE, BKERROR_WRONG_EXTRACT_FILE_TEXT },
    { BKERROR_WRITE_CACHE_OVERFLOWED, BKERROR_WRITE_CACHE_OVERFLOWED_TEXT },
    { BKERROR_CREATE_SYMLINK_FAILED, BKERROR_CREATE_SYMLINK_FAILED_TEXT },
    { BKERROR_SYMLINK_TARGET_TOO_LONG, BKERROR_SYMLINK_TARGET_TOO_LONG_TEXT },
    { BKERROR_HARD_LINK_CALL_PARAMS, BKERROR_HARD_LINK_CALL_PARAMS_TEXT },
    { BKERROR_NAME_INVALID, BKERROR_NAME_INVALID_TEXT },
    { BKERROR_RENAME_ROOT, BKERROR_RENAME_ROOT_TEXT },
    { BKERROR_ITEM_NOT_FOUND_ON_IMAGE, BKERROR_ITEM_NOT_FOUND_ON_IMAGE_TEXT },
    { BKERROR_DUPLICATE_RENAME, BKERROR_DUPLICATE_RENAME_TEXT },
    { BKERROR_GET_PERM_BAD_PARAM, BKERROR_GET_PERM_BAD_PARAM_TEXT },
    { BKERROR_EDITED_EXTRACT_TOO_BIG, BKERROR_EDITED_EXTRACT_TOO_BIG_TEXT },
    { BKERROR_EDITED_WRITE_TOO_BIG, BKERROR_EDITED_WRITE_TOO_BIG_TEXT },
    
    { BKWARNING_OPER_PARTLY_FAILED, BKWARNING_OPER_PARTLY_FAILED_TEXT },
    
    { BKERROR_END, BKERROR_END_TEXT }
};

const char* bk_get_error_string(int errorId)
{
    int count;
    
    for(count = 0; messageStructs[count].number != BKERROR_END; count++)
    {
        if(messageStructs[count].number == errorId)
            break;
    }
    
    if(messageStructs[count].number == BKERROR_END)
        printf("unknown error %d used\n", errorId);
    
    return messageStructs[count].text;
}

const char* bk_get_error_string_id(int errorId)
{
    /* Returns a stable string identifier for the error code.
     * UI layer can use this with gettext to display translated messages.
     * Format: "BKERROR_XXXXXXX" or "BKWARNING_XXXXXXX" */
    switch(errorId)
    {
        case BKERROR_READ_GENERIC: return "BKERROR_READ_GENERIC";
        case BKERROR_DIR_NOT_FOUND_ON_IMAGE: return "BKERROR_DIR_NOT_FOUND_ON_IMAGE";
        case BKERROR_MAX_NAME_LENGTH_EXCEEDED: return "BKERROR_MAX_NAME_LENGTH_EXCEEDED";
        case BKERROR_STAT_FAILED: return "BKERROR_STAT_FAILED";
        case BKERROR_TARGET_NOT_A_DIR: return "BKERROR_TARGET_NOT_A_DIR";
        case BKERROR_OUT_OF_MEMORY: return "BKERROR_OUT_OF_MEMORY";
        case BKERROR_OPENDIR_FAILED: return "BKERROR_OPENDIR_FAILED";
        case BKERROR_EXOTIC: return "BKERROR_EXOTIC";
        case BKERROR_FIXME: return "BKERROR_FIXME";
        case BKERROR_FILE_NOT_FOUND_ON_IMAGE: return "BKERROR_FILE_NOT_FOUND_ON_IMAGE";
        case BKERROR_MKDIR_FAILED: return "BKERROR_MKDIR_FAILED";
        case BKERROR_OPEN_WRITE_FAILED: return "BKERROR_OPEN_WRITE_FAILED";
        case BKERROR_WRITE_GENERIC: return "BKERROR_WRITE_GENERIC";
        case BKERROR_MANGLE_TOO_MANY_COL: return "BKERROR_MANGLE_TOO_MANY_COL";
        case BKERROR_MISFORMED_PATH: return "BKERROR_MISFORMED_PATH";
        case BKERROR_INVALID_UCS2: return "BKERROR_INVALID_UCS2";
        case BKERROR_UNKNOWN_FILENAME_TYPE: return "BKERROR_UNKNOWN_FILENAME_TYPE";
        case BKERROR_RR_FILENAME_MISSING: return "BKERROR_RR_FILENAME_MISSING";
        case BKERROR_VD_NOT_PRIMARY: return "BKERROR_VD_NOT_PRIMARY";
        case BKERROR_SANITY: return "BKERROR_SANITY";
        case BKERROR_OPEN_READ_FAILED: return "BKERROR_OPEN_READ_FAILED";
        case BKERROR_DIRNAME_NEED_TRAILING_SLASH: return "BKERROR_DIRNAME_NEED_TRAILING_SLASH";
        case BKERROR_EXTRACT_ROOT: return "BKERROR_EXTRACT_ROOT";
        case BKERROR_DELETE_ROOT: return "BKERROR_DELETE_ROOT";
        case BKERROR_DUPLICATE_ADD: return "BKERROR_DUPLICATE_ADD";
        case BKERROR_DUPLICATE_EXTRACT: return "BKERROR_DUPLICATE_EXTRACT";
        case BKERROR_NO_SPECIAL_FILES: return "BKERROR_NO_SPECIAL_FILES";
        case BKERROR_NO_POSIX_PRESENT: return "BKERROR_NO_POSIX_PRESENT";
        case BKERROR_EXTRACT_ABSENT_BOOT_RECORD: return "BKERROR_EXTRACT_ABSENT_BOOT_RECORD";
        case BKERROR_EXTRACT_UNKNOWN_BOOT_MEDIA: return "BKERROR_EXTRACT_UNKNOWN_BOOT_MEDIA";
        case BKERROR_ADD_UNKNOWN_BOOT_MEDIA: return "BKERROR_ADD_UNKNOWN_BOOT_MEDIA";
        case BKERROR_ADD_BOOT_RECORD_WRONG_SIZE: return "BKERROR_ADD_BOOT_RECORD_WRONG_SIZE";
        case BKERROR_WRITE_BOOT_FILE_4: return "BKERROR_WRITE_BOOT_FILE_4";
        case BKERROR_DUPLICATE_CREATE_DIR: return "BKERROR_DUPLICATE_CREATE_DIR";
        case BKERROR_NAME_INVALID_CHAR: return "BKERROR_NAME_INVALID_CHAR";
        case BKERROR_BLANK_NAME: return "BKERROR_BLANK_NAME";
        case BKERROR_ADD_FILE_TOO_BIG: return "BKERROR_ADD_FILE_TOO_BIG";
        case BKERROR_SAVE_OVERWRITE: return "BKERROR_SAVE_OVERWRITE";
        case BKERROR_OPER_CANCELED_BY_USER: return "BKERROR_OPER_CANCELED_BY_USER";
        case BKERROR_NOT_DIR_IN_PATH: return "BKERROR_NOT_DIR_IN_PATH";
        case BKERROR_WRONG_EXTRACT_FILE: return "BKERROR_WRONG_EXTRACT_FILE";
        case BKERROR_NOT_REG_FILE_FOR_BR: return "BKERROR_NOT_REG_FILE_FOR_BR";
        case BKERROR_WRITE_CACHE_OVERFLOWED: return "BKERROR_WRITE_CACHE_OVERFLOWED";
        case BKERROR_CREATE_SYMLINK_FAILED: return "BKERROR_CREATE_SYMLINK_FAILED";
        case BKERROR_SYMLINK_TARGET_TOO_LONG: return "BKERROR_SYMLINK_TARGET_TOO_LONG";
        case BKERROR_HARD_LINK_CALL_PARAMS: return "BKERROR_HARD_LINK_CALL_PARAMS";
        case BKERROR_NAME_INVALID: return "BKERROR_NAME_INVALID";
        case BKERROR_RENAME_ROOT: return "BKERROR_RENAME_ROOT";
        case BKERROR_ITEM_NOT_FOUND_ON_IMAGE: return "BKERROR_ITEM_NOT_FOUND_ON_IMAGE";
        case BKERROR_DUPLICATE_RENAME: return "BKERROR_DUPLICATE_RENAME";
        case BKERROR_GET_PERM_BAD_PARAM: return "BKERROR_GET_PERM_BAD_PARAM";
        case BKERROR_EDITED_EXTRACT_TOO_BIG: return "BKERROR_EDITED_EXTRACT_TOO_BIG";
        case BKERROR_EDITED_WRITE_TOO_BIG: return "BKERROR_EDITED_WRITE_TOO_BIG";
        case BKWARNING_OPER_PARTLY_FAILED: return "BKWARNING_OPER_PARTLY_FAILED";
        case BKERROR_END: return "BKERROR_END";
        default: return "BKERROR_UNKNOWN";
    }
}
